require'nvim-treesitter.configs'.setup {
    ensure_installed = {
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "comment",
        "commonlisp",
        "cpp",
        "css",
        "dockerfile",
        "elixir",
        "erlang",
        "go",
        "gomod",
        "graphql",
        "html",
        "http",
        "java",
        "javascript",
        "jsdoc",
        "json",
        "jsonc",
        "julia",
        "kotlin",
        "latex",
        "llvm",
        "lua",
        "nix",
        "ocaml",
        "ocaml_interface",
        "perl",
        "php",
        "python",
        "ql",
        "query",
        "r",
        "regex",
        "ruby",
        "rust",
        "scala",
        "tsx",
        "typescript",
        "vim",
        "vue",
        "yaml",
        "zig",
    },
    indent = {
        enable = true
    },
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
    incremental_selection = {
        enable = true
    },
    textobjects = {
        enable = true
    }
}
