#!/bin/sh

##COMPETITIVE/C++
alias m='make && make t'
alias c='g++ -std=c++20 -O3 -Wshadow -Wall -Wno-unused-result -Wno-sign-compare -Wno-char-subscripts'
alias cd='g++ -std=c++20 -Wshadow -Wall -Wno-unused-result -Wno-sign-compare -Wno-char-subscripts -g -Og -fsanitize=address,undefined -D_GLIBCXX_DEBUG'
alias cw='g++ -std=c++20 -O3 -Wfatal-errors -Wno-unused-result -Wno-sign-compare -Wno-char-subscripts'
alias getcppincludepaths='g++ -E -x c++ - -v < /dev/null'
