#!/bin/sh

function extract(){
    # Bash Function To Extract File Archives Of Various Types
     if [ -f $1 ] ; then
         case $1 in
             *.tar.bz2)   tar xjf $1     ;;
             *.tar.gz)    tar xzf $1     ;;
             *.bz2)       bunzip2 $1     ;;
             *.rar)       rar x $1       ;;
             *.gz)        gunzip $1      ;;
             *.tar)       tar xf $1      ;;
             *.tbz2)      tar xjf $1     ;;
             *.tgz)       tar xzf $1     ;;
             *.zip)       unzip $1       ;;
             *.Z)         uncompress $1  ;;
             *.7z)        7z x $1    ;;
             *)           echo "'$1' cannot be extracted via extract()" ;;
         esac
     else
         echo "'$1' is not a valid file"
     fi
}

function deb-install(){
   # telegram.deb
   sudo dpkg -i $1
}

function deb-uninstall(){
    # telegram
   sudo dpkg -r $1
}

function swap-java(){
    sudo update-alternatives --config java
    sudo update-alternatives --config javac
}
