vim.keymap.set("n", "]f", "<nop>", { desc = "Disable default ]f" })
vim.keymap.set("n", "[f", "<nop>", { desc = "Disable default [f" })

-- vim.pack.add({
--     'https://github.com/nvim-treesitter/nvim-treesitter',
--     'https://github.com/nvim-treesitter/nvim-treesitter-textobjects',
-- })
--
-- require('nvim-treesitter.configs').setup({
--     ensure_installed = {
--         "bash", "comment", "lua", "luadoc", "vim", "vimdoc", "diff", "gitcommit", "markdown", "markdown_inline",
--         "xml", "yaml",
--         "javascript", "typescript", "go", "c", "cpp", "python", "kotlin", "java", "html", "jsdoc", "rust", "sql",
--         "tsx",
--     },
--     sync_install = false,
--     indent = { enable = true },
--     highlight = { enable = true },
--     textobjects = {
--         enable = true,
--         select = {
--             enable = true,
--             lookahead = true,
--             keymaps = {
--                 ["af"] = "@function.outer",
--                 ["if"] = "@function.inner",
--                 ["ac"] = "@class.outer",
--                 ["ic"] = "@class.inner",
--             },
--         },
--         move = {
--             enable = true,
--             set_jumps = true,
--             goto_next_start = { [']f'] = '@function.outer', [']c'] = '@class.outer' },
--             goto_previous_start = { ['[f'] = '@function.outer', ['[c'] = '@class.outer' },
--         },
--         swap = {
--             enable = true,
--             swap_next = { ["<leader>sw"] = "@parameter.inner" },
--         }
--     }
-- })
